### ISSUE TITLE
Ошибка в конспекте

### ISSUE THREAD

**Issue by AlexandraOlegovna** [xamgore/au-java-lectures#1]
Ребят, кажется у вас [ошибка](https://xamgore.github.io/au-java-lectures/lectures/01_words.html?p=L2h0bWxbMV0vYm9keS9hcnRpY2xlL3ByZVs2XS9jb2RlL3NwYW4%3D) во фразе `for (String str : args) {
        System.out.println("Hello, " + str);
        }`, в параграфе:
> for

тут нужен отступ перед System

**Comment by xamgore** [comment]
Исправлено.
